### PR TITLE
Test pipeline setup

### PR DESCRIPTION
**Pull request by navinkrishnan**
Adjusted Remote service & messaging add scripts to inject delta parts to package.json rather than replacing it.

### CODE REVIEW

**Comment by navinkrishnan** [comment]
@DanSchlachter Can you pls check and merge this ? Need this change for the monorepo.

**Comment by DanSchlachter** [comment]
can you make the checkout file less prominent (hidden or not in main dir)?

**Comment by navinkrishnan** [comment]
was thinking same. how about under `.github/workflows` ?

**Comment by DanSchlachter** [comment]
> was thinking same. how about under `.github/workflows` ?

yes, that's better

**Comment by navinkrishnan** [comment]
check now

**Review by DanSchlachter — APPROVED** [review]

**Pull request merged**
